version: "3.9"
services:
  user-api:
    build: .
    image: configparser-user-api
    depends_on:
      - es01
    ports:
      - "8085:8080/tcp"
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - node.name=es01
      - discovery.type=single-node
      - network.host=0.0.0.0
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
    depends_on:
      - es01
    ports:
      - 5601:5601